name: Build and deploy ASP.Net Core app to Azure Web App - gabtrans

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Locate .csproj file automatically
      - name: Locate project file
        id: find-project
        shell: bash
        run: |
          PROJECT_FILE=$(find . -maxdepth 7 -name "*.csproj" | head -n 1)
          echo "project=$PROJECT_FILE" >> $GITHUB_OUTPUT

      # Build project
      - name: Build with dotnet
        run: dotnet build "${{ steps.find-project.outputs.project }}" -c Release

      # Publish to a local folder (publish output)
      - name: dotnet publish
        run: dotnet publish "${{ steps.find-project.outputs.project }}" -c Release -o publish
     
  # Deploy directly to Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'gabtrans-platform'
          slot-name: 'Production'
          package: publish
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1A22C55713994570A997B06DCE3A6724 }}
